@startuml QRAuth Autentication
header
last-updated 05/03/2020
end header
title
QRAuth Autentication
end title
footer
authored by Vincent BILLET
end footer

actor Mobile
Browser -> App: GET App frontpage
Browser <-- App: frontpage
Browser -> QRAuthServer: WebSocket request AuthBox
Browser <-- QRAuthServer: AuthBox
Browser -> Browser: Generate Random QRCode
Mobile <- Browser: Scan QRCode
Mobile -> QRAuthServer: Send QRCode
Mobile <-- QRAuthServer: CloseAuthApp
Browser <-- QRAuthServer: API Response, Close AuthBox
Browser -> App : GET /ajax_api?
App -> QRAuthServer : GET /me?access_token
App <-- QRAuthServer : API Response
Browser <-- App : Display UserData
@enduml